Quejas_Proyecto/Controllers/comerciosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Quejas_Proyecto.context;

namespace Quejas_Proyecto.Controllers
{
    [Authorize]
    public class comerciosController : Controller
    {
        private quejasEntities db = new quejasEntities();

        // GET: comercios
        public ActionResult Index()
        {
            return View(db.comercios.ToList());
        }

        // GET: comercios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comercio comercio = db.comercios.Find(id);
            if (comercio == null)
            {
                return HttpNotFound();
            }
            return View(comercio);
        }

        // GET: comercios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: comercios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idcomercio,nombre_comercio")] comercio comercio)
        {
            if (ModelState.IsValid)
            {
                db.comercios.Add(comercio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(comercio);
        }

        // GET: comercios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comercio comercio = db.comercios.Find(id);
            if (comercio == null)
            {
                return HttpNotFound();
            }
            return View(comercio);
        }

        // POST: comercios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idcomercio,nombre_comercio")] comercio comercio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comercio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(comercio);
        }

        // GET: comercios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comercio comercio = db.comercios.Find(id);
            if (comercio == null)
            {
                return HttpNotFound();
            }
            return View(comercio);
        }

        // POST: comercios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            comercio comercio = db.comercios.Find(id);
            db.comercios.Remove(comercio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Quejas_Proyecto/Controllers/quejasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Quejas_Proyecto.context;

namespace Quejas_Proyecto.Controllers
{
    public class quejasController : Controller
    {
        private quejasEntities db = new quejasEntities();

        // GET: quejas
     /*   public ActionResult Index()
        {
            var quejas = db.quejas.Include(q => q.sucursal);
            return View(quejas.ToList());
        }*/

        // GET: quejas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            queja queja = db.quejas.Find(id);
            if (queja == null)
            {
                return HttpNotFound();
            }
            return View(queja);
        }

        public List<departamento> GetDepartamentoList()
        {

            List<departamento> departamentos = db.departamentoes.ToList();
            return departamentos;
        }
        public ActionResult GetMunicipioSucursal(int Depa)
        {
            List<municipio> selectlist = db.municipios.Where(m => m.iddepartamento == Depa).ToList();
            ViewBag.MuniListSucursal = new SelectList(selectlist, "idmunicipio", "nombre_municipio");
            return PartialView("DisplayMuniSucursal");
        }
        public ActionResult GetSucursal(int ComeId,int Munici_id)
        {
            List<sucursal> seleclist = db.sucursals.Where(m => m.idcomercio == ComeId).Where(m => m.idmunicipio == Munici_id).ToList();
            ViewBag.sucursalList = new SelectList(seleclist, "idsucursal", "nombre_sucursal");
            return PartialView("DisplaySucursal");
        }
        public ActionResult GetComercio(int Munic)
        {
            List<sucursal> seleclist = db.sucursals.Where(m => m.idmunicipio == Munic).ToList();
          /*  var fields = new List<SelectListItem>();
            for (int i = 0; i < seleclist.Count; i++)
            {

                fields.Add(
                    new SelectListItem
                    {
                        Text = seleclist[i].comercio.nombre_comercio,
                        Value = seleclist[i].comercio.idcomercio.ToString()
                    }); ;
            }*/
            ViewBag.SucursalComercio = new SelectList(seleclist, "comercio.idcomercio","comercio.nombre_comercio");
            //ViewBag.SucursalComercio = fields;
            return PartialView("DisplayComercio");
        }

        // GET: quejas/Create
        public ActionResult Create()
        {
            ViewBag.idsucursal = new SelectList(db.sucursals, "idsucursal", "nombre_sucursal");
            ViewBag.GetDepa = new SelectList(GetDepartamentoList(), "iddepartamento", "nombre_departamento");
            return View();
        }

        // POST: quejas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( queja_dep_sucursal queja)
        {
            if (ModelState.IsValid)
            {
                db.quejas.Add(queja.QuejaView);
                db.SaveChanges();
                TempData["Message"] = "Registrado correctamente";
                return RedirectToAction("Create");
            }

            ViewBag.idsucursal = new SelectList(db.sucursals, "idsucursal", "nombre_sucursal", queja.QuejaView.idsucursal);
            ViewBag.GetDepa = new SelectList(GetDepartamentoList(), "iddepartamento", "nombre_departamento");
            return View(queja.QuejaView);
        }

    /*    // GET: quejas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            queja queja = db.quejas.Find(id);
            if (queja == null)
            {
                return HttpNotFound();
            }
            ViewBag.idsucursal = new SelectList(db.sucursals, "idsucursal", "nombre_sucursal", queja.idsucursal);
            return View(queja);
        }

        // POST: quejas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idqueja,idsucursal,queja1,fecha_queja")] queja queja)
        {
            if (ModelState.IsValid)
            {
                db.Entry(queja).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idsucursal = new SelectList(db.sucursals, "idsucursal", "nombre_sucursal", queja.idsucursal);
            return View(queja);
        }

        // GET: quejas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            queja queja = db.quejas.Find(id);
            if (queja == null)
            {
                return HttpNotFound();
            }
            return View(queja);
        }

        // POST: quejas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            queja queja = db.quejas.Find(id);
            db.quejas.Remove(queja);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }*/
    }
}

Quejas_Proyecto/Controllers/sucursalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Quejas_Proyecto.context;

namespace Quejas_Proyecto.Controllers
{
    [Authorize]
    public class sucursalController : Controller
    {
        private quejasEntities db = new quejasEntities();

        // GET: sucursal
        public ActionResult Index()
        {
            var sucursals = db.sucursals.Include(s => s.comercio).Include(s => s.municipio);
            return View(sucursals.ToList());
        
        }
    

     
        public List<departamento> GetDepartamentoList()
        {
           
            List<departamento> departamentos = db.departamentoes.ToList();
            return departamentos;
        }
        public ActionResult GetMunicipio(int Depa)
        {
            List<municipio> selectlist = db.municipios.Where(m => m.iddepartamento == Depa).ToList();
            ViewBag.MuniList = new SelectList(selectlist, "idmunicipio", "nombre_municipio");
            return PartialView("DisplayMuni");
        }

        // GET: sucursal/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sucursal sucursal = db.sucursals.Find(id);
            if (sucursal == null)
            {
                return HttpNotFound();
            }
            return View(sucursal);
        }

        // GET: sucursal/Create
        public ActionResult Create()
        {
            ViewBag.idcomercio = new SelectList(db.comercios, "idcomercio", "nombre_comercio");
            ViewBag.idmunicipio = new SelectList(db.municipios, "idmunicipio", "nombre_municipio");
             ViewBag.depas = new SelectList(GetDepartamentoList(), "iddepartamento", "nombre_departamento");
          

            return View();
        }

        // POST: sucursal/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(depa_sucursal sucursal)
        {
            if (ModelState.IsValid)
            {
                db.sucursals.Add(sucursal.SucursalView);
                db.SaveChanges();
                TempData["Message"] = "Registrado correctamente";

                return RedirectToAction("Create");

            }


            return View();
            
        }

        // GET: sucursal/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sucursal sucursal = db.sucursals.Find(id);
            if (sucursal == null)
            {
                return HttpNotFound();
            }
            ViewBag.idcomercio = new SelectList(db.comercios, "idcomercio", "nombre_comercio", sucursal.idcomercio);
            ViewBag.idmunicipio = new SelectList(db.municipios, "idmunicipio", "nombre_municipio", sucursal.idmunicipio);
            return View(sucursal);
        }

        // POST: sucursal/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idsucursal,idcomercio,idmunicipio,nombre_sucursal")] sucursal sucursal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sucursal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idcomercio = new SelectList(db.comercios, "idcomercio", "nombre_comercio", sucursal.idcomercio);
            ViewBag.idmunicipio = new SelectList(db.municipios, "idmunicipio", "nombre_municipio", sucursal.idmunicipio);
            return View(sucursal);
        }

        // GET: sucursal/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sucursal sucursal = db.sucursals.Find(id);
            if (sucursal == null)
            {
                return HttpNotFound();
            }
            return View(sucursal);
        }

        // POST: sucursal/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            sucursal sucursal = db.sucursals.Find(id);
            db.sucursals.Remove(sucursal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Quejas_Proyecto/Views/Shared/DisplayComercio.cshtml
@model Quejas_Proyecto.context.comercio

<option value="">Seleccione Comercio</option>

@if (ViewBag.SucursalComercio != null)
{
    foreach (var item in ViewBag.SucursalComercio)
    {

        <option value="@item.Value">@item.Text</option>
        
    }
}

Quejas_Proyecto/Views/Shared/DisplayMuni.cshtml
@model Quejas_Proyecto.context.municipio

<option value="">Seleccione Municipio</option>

@if(ViewBag.MuniList != null)
            {
                foreach(var item in ViewBag.MuniList)
                {

        <option value="@item.Value">@item.Text</option>

    }
    }

Quejas_Proyecto/Views/Shared/DisplayMuniSucursal.cshtml
@model Quejas_Proyecto.context.municipio
    <option value="">Seleccione Municipio</option>



    @if (ViewBag.MuniListSucursal != null)
    {
        foreach (var item in ViewBag.MuniListSucursal)
        {
           
                <option value="@item.Value">@item.Text</option>
           
        }
    }

Quejas_Proyecto/Views/Shared/DisplaySucursal.cshtml
@model Quejas_Proyecto.context.sucursal

<option value="">Seleccione Sucursal</option>

@if (ViewBag.sucursalList != null)
{
    foreach (var item in ViewBag.sucursalList)
    {
        <option value="@item.Value">@item.Text</option>
    }
}

Quejas_Proyecto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
   
    @Scripts.Render("~/bundles/modernizr")

  
    <!-- Compiled and minified CSS -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>



</head>
<body>
    <!-- <nav>
         <div class="container">
             <div class="navbar-header">
                 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                 </button>
                 @Html.ActionLink("Gestion de Quejas", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
             </div>

             <div>
                 <ul class="nav-wrapper">
                     <li>@Html.ActionLink("Home", "Index", "Home")</li>
                     <li>@Html.ActionLink("Comercio", "Index", "comercios")</li>
                     <li>@Html.ActionLink("Sucursal", "Index", "sucursal")</li>
                     <li>@Html.ActionLink("Queja", "Index", "quejas")</li>
                     <li>@Html.ActionLink("Consulta", "Consulta_btn", "Consulta")</li>
                     <li>@Html.ActionLink("Fechas", "Getquejas", "Consulta")</li>



                 </ul>
                 @Html.Partial("_LoginPartial")
                 <ul class="nav nav-tabs">
                     <li class="dropdown">
                         <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                             Estadisticas
                             <span class="caret"></span>
                         </a>
                         <ul class="dropdown-menu">
                             <li>@Html.ActionLink("Municipio", "PorMunicipio", "Consulta")</a></li>
                             <li>@Html.ActionLink("Departamento", "PorDepartamento", "Consulta")</li>
                             <li>@Html.ActionLink("Region", "PorRegion", "Consulta")</li>
                             <li>@Html.ActionLink("Comercio", "PorComercio", "Consulta")</li>

                         </ul>
                     </li>

                 </ul>



             </div>


         </div>
     </nav>-->

    <nav>
        <div class="nav-wrapper red accent-4">
            <div class="container">
                <a href="~/Home/Index" class="brand-logo"><i class="material-icons left">sentiment_very_dissatisfied</i> Quejas</a>
                <ul class="right hide-on-med-and-down">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Comercio", "Index", "comercios")</li>
                        <li>@Html.ActionLink("Sucursal", "Index", "sucursal")</li>
                        <li>@Html.ActionLink("Consulta", "Consulta_btn", "Consulta")</li>
                        <li>@Html.ActionLink("Fechas", "Getquejas", "Consulta")</li>
                        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Estadisticas<i class="material-icons right">arrow_drop_down</i></a></li>
                        
                    }

                    <li>@Html.ActionLink("Queja", "Create", "quejas")</li>


                    <!-- Dropdown Trigger -->

                    <li>  @Html.Partial("_LoginPartial")</li>

                </ul>




            </div>

        </div>
        <!-- Dropdown Structure -->
        <ul id="dropdown1" class="dropdown-content">
            <li>@Html.ActionLink("Municipio", "PorMunicipio", "Consulta")</a></li>
            <li>@Html.ActionLink("Departamento", "PorDepartamento", "Consulta")</li>
            <li>@Html.ActionLink("Region", "PorRegion", "Consulta")</li>
            <li>@Html.ActionLink("Comercio", "PorComercio", "Consulta")</li>
        </ul>

    </nav>



    <div class="container body-content">
        @RenderBody()

        <br />
        <footer>
            <p>&copy; @DateTime.Now.Year - Quejas Application</p>
        </footer>
    </div>
    <script>   document.addEventListener('DOMContentLoaded', function () {
       M.AutoInit();
        });
</script>
 


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)



</body>
</html>

Quejas_Proyecto/Views/Shared/_ListaQuejaFecha.cshtml
@model Quejas_Proyecto.context.queja
<table class="responsive-table  striped">
    
        <tr>
            <th>Queja</th>
            <th>Fecha</th>
            <th>Comercio</th>
        </tr>
   

    @foreach (var queja in ViewBag.ListaQueja)
    {

     

            <tr>

                <td>@queja.queja1</td>
                <td>@queja.fecha_queja</td>
                <td>@queja.sucursal.comercio.nombre_comercio</td>
            </tr>

        


    }
</table>